name: sistem_presensi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.7.2
  intl: ^0.20.2
  shared_preferences: ^2.3.3
  http: ^1.4.0
  file_picker: ^10.2.0
  camera: ^0.10.6
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/